#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

Ticketing:
  path: /ticketing/
  controller: App\Controller\TicketingController::index

Pannier:
  path: /ticketing/pannier
  controller: App\Controller\TicketingController::pannier