#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

Ticketing:
  path: /billeterie/
  controller: App\Controller\TicketingController::index
