#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: [/{_locale}, /]
  controller: App\Controller\HomeController::index
  requirements:
    _locale: fr|en

Ticketing:
  path: /{_locale}/ticketing
  controller: App\Controller\TicketingController::index
  requirements:
    _locale: fr|en

Pannier:
  path: /{_locale}/ticketing/pannier
  controller: App\Controller\TicketingController::pannier
  requirements:
    _locale: fr|en